# Generated by Django 3.2 on 2021-06-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_form_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lemma',
            old_name='lemma',
            new_name='name',
        ),
    ]
