# Generated by Django 3.2 on 2021-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_form_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='latin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
