# Generated by Django 3.2 on 2021-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
