# Generated by Django 3.2 on 2021-06-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_lemma_lemma_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='form',
            new_name='name',
        ),
    ]
