# Generated by Django 3.2 on 2021-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210515_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrolexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100, null=True)),
                ('F_bfm', models.CharField(max_length=100, null=True)),
                ('F_dmf', models.CharField(max_length=100, null=True)),
                ('msd_afrlex', models.CharField(max_length=100, null=True)),
                ('msd_bfm', models.CharField(max_length=100, null=True)),
                ('msd_cattex_conv1', models.CharField(max_length=100, null=True)),
                ('msd_cattex_conv2', models.CharField(max_length=100, null=True)),
                ('lemma', models.CharField(max_length=100, null=True)),
                ('lamma_src', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataRow',
        ),
    ]
