# Generated by Django 3.2 on 2021-05-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210515_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frolexentry',
            old_name='lamma_src',
            new_name='lemma_src',
        ),
    ]
