# Generated by Django 3.2 on 2021-05-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_lamma_src_frolexentry_lemma_src'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frolexentry',
            options={'managed': False},
        ),
    ]
