# Generated by Django 3.2 on 2021-05-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_frolexentry_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='frolexentry',
            table='search_frolexentry',
        ),
    ]
