# Generated by Django 3.2 on 2021-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lemma', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
