# Generated by Django 3.2 on 2021-06-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_form_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['lemma']},
        ),
    ]
