# Generated by Django 3.2 on 2021-06-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_form_latin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
    ]
