# Generated by Django 3.2 on 2021-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HyperbaseQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_id', models.CharField(help_text='Base ID', max_length=100)),
                ('corpus', models.CharField(help_text='Description of the corpus', max_length=100)),
                ('query', models.CharField(help_text='Word / code / lemma or expression (in quotes)', max_length=100)),
            ],
        ),
    ]
